spring:
  application:
    name: ead-notification-service
  config:
    import: 'configserver:' # the eureka client will get the uri, if config server is unavailable then, the service will use the local configuration
  cloud:
    config:
      discovery:
        serviceId: ead-config-server
      username: configserver
      password: 'ead123cs'