server:
  port: 8082

spring:
  application:
    name: ead.course-service
  datasource:
    url:  jdbc:postgresql://localhost:5432/ead-course
    username: postgres
    password: ead1234
  jpa:
    hibernate:
      ddl-auto: update # generate the tables automatically
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true # show all sql transactions
  output:
    ansi:
      enabled: Always

logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

ead:
  api:
    url:
      authuser: 'http://ead.authuser-service'

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost
