server:
  port: 8888

spring:
  application:
    name: ead-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/umbertomif/ead-config-server-repo
          default-label: main
          username: umbertomif
          password: **********

eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka"
  instance:
    hostname: localhost

